# Generated by Django 5.0.6 on 2026-05-14 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('case_family', models.CharField(choices=[('employee_disciplinary', 'Employee Internal Disciplinary'), ('serious_misconduct_employee', 'Serious Misconduct — Employee'), ('temporary_suspension', 'Temporary Suspension'), ('grievance', 'Grievance Process'), ('senior_serious_misconduct', 'Senior Executive — Serious Misconduct'), ('senior_poor_performance', 'Senior Executive — Poor Performance')], max_length=40)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_hold', 'On Hold'), ('closed', 'Closed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('subject_name', models.CharField(max_length=200)),
                ('subject_position', models.CharField(blank=True, max_length=200)),
                ('subject_ministry', models.CharField(blank=True, max_length=200)),
                ('is_senior_executive', models.BooleanField(default=False)),
                ('date_received', models.DateField()),
                ('date_opened', models.DateTimeField(auto_now_add=True)),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('initiating_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_opened'],
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decided_by_role', models.CharField(max_length=50)),
                ('decided_by_name', models.CharField(max_length=200)),
                ('outcome', models.CharField(choices=[('reinstate', 'Reinstated'), ('terminate', 'Terminated / Dismissed'), ('warn', 'Formal Warning Issued'), ('demote', 'Demotion'), ('suspend_no_pay', 'Suspension Without Pay'), ('compulsory_retire', 'Compulsory Retirement'), ('no_action', 'No Further Action'), ('referred_psdb', 'Referred to PSDB'), ('settled', 'Settled (Grievance)'), ('not_settled', 'Not Settled (Grievance)')], max_length=30)),
                ('decided_at', models.DateField()),
                ('narrative', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-decided_at'],
            },
        ),
        migrations.CreateModel(
            name='LitigationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('legal_counsel', models.CharField(blank=True, max_length=200)),
                ('court_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('settled', 'Settled'), ('dismissed', 'Dismissed'), ('judgment', 'Judgment Issued')], default='active', max_length=20)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_initiated', models.DateField()),
                ('date_resolved', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litigation_records', to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='CaseStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=150)),
                ('stage_order', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('sla_status', models.CharField(choices=[('on_track', 'On Track'), ('at_risk', 'At Risk'), ('overdue', 'Overdue'), ('completed', 'Completed')], default='on_track', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_assignments', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='cases.case')),
            ],
            options={
                'ordering': ['stage_order'],
                'unique_together': {('case', 'stage_order')},
            },
        ),
    ]
