# Generated by Django 6.0.5 on 2026-05-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_portal_approval_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='cdp_callback_url',
            field=models.URLField(blank=True, default='', help_text='SCDMS callback URL (reserved; CMS does not drive Secretary review after sync).', max_length=500),
        ),
    ]
