# Generated by Django 6.0.5 on 2026-05-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='timezone_display',
            field=models.CharField(default='Pacific/Efate (UTC+11)', help_text='Display label; Django TIME_ZONE remains authoritative.', max_length=64),
        ),
    ]
